"""Generate fake employee records that look like a real HR system export.

Real companies keep employees in an HR system (Workday, BambooHR, ADP). We must
never copy real people into a lab, so we generate records that follow the same
rules the real data follows:

    - the same columns an HR export would have
    - every employee reports to a manager, so the org chart is real
    - every salary sits inside the band for its level (Compensation Bands 2026)
    - bonus targets follow the policy: 5% (L1-L3), 10% (L4-L5), 15% (L6), 20% (L7-L8)
    - names and emails are fake, and the same seed always gives the same people

Usage (from the project folder):

    docker run --rm -v ./db:/db python:3.12-slim sh -c \
        "pip install --quiet faker && python /db/generate_employees.py 50 > /db/03_generated_employees.sql"

Then load the file into Aurora, through the bastion:

    psql "$DATABASE_ADMIN_URL" -f db/03_generated_employees.sql
"""

import random
import sys

from faker import Faker

# Salary bands from the Compensation Bands 2026 policy: level -> (minimum, maximum)
BANDS = {
    "L1": (68000, 84000), "L2": (82000, 103000), "L3": (99000, 128000), "L4": (124000, 158000),
    "L5": (152000, 192000), "L6": (186000, 236000),
}
BONUS = {"L1": 5, "L2": 5, "L3": 5, "L4": 10, "L5": 10, "L6": 15}

# New people join existing teams, so the access rules keep working:
# department -> (manager's employee_id, job titles by level)
TEAMS = {
    "Engineering": ("NW-1003", {"L2": "Software Engineer I", "L3": "Software Engineer II",
                                "L4": "Senior Software Engineer", "L5": "Staff Software Engineer"}),
    "Sales": ("NW-1004", {"L1": "Sales Development Representative", "L3": "Account Executive",
                          "L4": "Senior Account Executive"}),
    "People Operations": ("NW-1002", {"L2": "HR Coordinator", "L3": "Recruiter", "L4": "HR Business Partner"}),
}
LOCATIONS = ["Austin, TX", "Chicago, IL", "New York, NY", "Remote - Denver, CO"]


def sql_text(value):
    """Put a value in single quotes for SQL, doubling any quote inside it (O'Brien -> O''Brien)."""
    return "'" + str(value).replace("'", "''") + "'"


def main():
    count = int(sys.argv[1]) if len(sys.argv) > 1 else 20

    # A fixed seed means every environment generates exactly the same people
    fake = Faker()
    Faker.seed(42)
    random.seed(42)

    used_emails = set()
    rows = []
    for number in range(count):
        department = random.choice(list(TEAMS))
        manager_id, titles = TEAMS[department]
        level = random.choice(list(titles))
        low, high = BANDS[level]

        # Make sure no two people get the same email
        while True:
            first, last = fake.first_name(), fake.last_name()
            email = f"{first}.{last}@northwind.example".lower().replace("'", "")
            if email not in used_emails:
                used_emails.add(email)
                break

        values = [
            sql_text(f"NW-{2001 + number}"),
            sql_text(email),
            sql_text(f"{first} {last}"),
            sql_text("employee"),
            sql_text(department),
            sql_text(titles[level]),
            sql_text(level),
            sql_text(manager_id),
            sql_text(random.choice(LOCATIONS)),
            sql_text(fake.date_between(start_date="-9y", end_date="-30d")),
            str(round(random.randint(low, high), -3)),      # salary inside the band, rounded to 1,000
            str(BONUS[level]),
            str(random.randint(0, 52) / 2),                  # 0 to 26 days, in half days
        ]
        rows.append("    (" + ", ".join(values) + ")")

    print("-- Generated by db/generate_employees.py. Fake people, realistic rules.")
    print("INSERT INTO employees")
    print("    (employee_id, email, full_name, role, department, job_title, job_level,")
    print("     manager_id, location, hire_date, base_salary, bonus_target_percent, pto_days_remaining)")
    print("VALUES")
    print(",\n".join(rows) + ";")


if __name__ == "__main__":
    main()
